#!/usr/bin/env julia

"""
Generate every printable exercise artifact from the shared exercise content.

Usage:
    julia --project=. scripts/generate_exercise_materials.jl
    julia --project=. scripts/generate_exercise_materials.jl --no-pdf

The PDF step uses an installed Chromium-based browser as a print engine. No
exercise text or answer is duplicated in this renderer.
"""

const ROOT = normpath(joinpath(@__DIR__, ".."))
const CONTENT_PATH = joinpath(ROOT, "notebooks", "ExerciseContent.jl")
include(CONTENT_PATH)
using .ExerciseContent
include(joinpath(@__DIR__, "BrowserPrint.jl"))
using .BrowserPrint

const EXERCISE_DIR = joinpath(ROOT, "exercises")
const ANSWER_DIR = joinpath(ROOT, "instructor")
const CONTENT_LABEL = "notebooks/ExerciseContent.jl"
const EXERCISE_NOTEBOOK_LABEL = "notebooks/05_ExerciseSheet.jl"

escape_html(text::AbstractString) =
    replace(text, '&' => "&amp;", '<' => "&lt;", '>' => "&gt;", '"' => "&quot;")

function inline_html(text::AbstractString)
    escaped = escape_html(text)
    escaped = replace(escaped, r"`([^`]+)`" => s"<code>\1</code>")
    replace(escaped, '\n' => "<br>")
end

function exercise_heading(exercise)
    location = isempty(exercise.location) ? "" : ", $(exercise.location)"
    "**Use:** `$(exercise.notebook)`$location\n\n**Time:** about $(exercise.minutes) minutes"
end

function student_markdown()
    out = String[
        "<!-- GENERATED from $CONTENT_LABEL. Do not edit this file directly. -->",
        "# $WORKSHEET_TITLE",
        "",
        "**$WORKSHEET_AUTHOR**",
        "",
        "## Exercise sheet",
        "",
        "**Time:** 30–40 minutes",
        "",
        "**Format:** 6 guided exercises",
        "",
        "**Difficulty:** introductory; no proofs and no code from scratch",
        "",
        "Open the named Pluto notebook, run only the relevant experiment, observe the visual result, and answer briefly. The interactive version is `$EXERCISE_NOTEBOOK_LABEL`.",
        "",
        "The goal is to distinguish the represented object, its coordinates, the model assumption, and the evidence needed before interpreting components.",
    ]
    for exercise in EXERCISES
        append!(out, ["", "---", "", "## Exercise $(exercise.number) — $(exercise.title)", "", exercise_heading(exercise), "", exercise.introduction])
        for section in exercise.sections
            isempty(section.title) || append!(out, ["", "### $(section.title)"])
            isempty(section.introduction) || append!(out, ["", section.introduction])
            for question in section.questions
                append!(out, ["", "$(question.id). $(question.prompt)"])
                for option in question.options
                    push!(out, "   - [ ] $option")
                end
                isempty(question.options) && append!(out, fill("   ________________________________________________________________________", question.answer_lines))
            end
        end
    end
    append!(out, [
        "", "---", "", "### Source note", "",
        "The themes are adapted at an introductory level from Paul Breiding's Tensorlab exercises. The questions are rederived for TensorKitchen and are not verbatim copies.",
    ])
    join(out, "\n") * "\n"
end

function answer_markdown()
    out = String[
        "<!-- GENERATED from $CONTENT_LABEL. Do not edit this file directly. -->",
        "# Exercise sheet — short answer key",
        "",
        "**$WORKSHEET_AUTHOR**",
    ]
    for exercise in EXERCISES
        append!(out, ["", "## Exercise $(exercise.number) — $(exercise.title)"])
        for section in exercise.sections, question in section.questions
            push!(out, "")
            push!(out, "**$(question.id).** $(question.answer)")
        end
    end
    join(out, "\n") * "\n"
end

const PRINT_CSS = """
@page { size: A4; margin: 14mm 15mm 16mm; }
* { box-sizing: border-box; }
body { margin: 0; color: #2e3224; background: white; font-family: Arial, Helvetica, sans-serif; font-size: 10pt; line-height: 1.38; }
.banner { margin: 0 0 7mm; padding: 7mm 9mm 6.5mm; color: white; background: linear-gradient(120deg, #4e5834, #70794c); border-bottom: 3px solid #b4773c; border-radius: 0 0 4mm 4mm; }
.banner h1 { margin: 0; font-size: 23pt; line-height: 1.05; }
.banner .author { margin-top: 1.5mm; color: #fff2d8; font-size: 10pt; font-weight: 600; letter-spacing: .02em; }
.banner p { margin: 1.5mm 0 0; color: #e8ebd9; font-size: 10.5pt; }
.intro { padding: 4mm 5mm; background: #f7f4e8; border: 1px solid #d9d3b8; border-radius: 3mm; margin-bottom: 6mm; }
.intro p { margin: 0 0 2mm; }.intro p:last-child { margin-bottom: 0; }
.exercise { width: 100%; min-width: 0; max-width: 100%; margin: 0 0 7mm; }
.exercise-head { break-inside: avoid; break-after: avoid; background: #5e6740; color: white; padding: 3.2mm 4mm; border-radius: 0; }
.exercise-head h2 { margin: 0; font-size: 14pt; }.meta { color: #e4e8d4; font-size: 8.4pt; margin-top: 1mm; }
.exercise-body { border: 1px solid #d5d9c3; border-top: 0; border-radius: 0 0 2.5mm 2.5mm; padding: 3.8mm 4.5mm; }
.exercise-body > p:first-child { margin-top: 0; }.exercise-body h3 { break-after: avoid; color: #59623d; font-size: 11pt; margin: 4mm 0 1.5mm; border-bottom: 1px solid #d9dec6; }
.question { break-inside: avoid; padding: 2mm 2.5mm; margin: 1.8mm 0; background: #f4f6ec; border-left: 2.5px solid #b4773c; border-radius: 1.5mm; }
.question p { margin: 0; }.qid { color: #55603a; font-weight: bold; }.options { max-width: 100%; margin: 1.4mm 0 0 2mm; display: flex; flex-wrap: wrap; gap: 1mm 6mm; }.box { color: #59604d; white-space: normal; }
.answer-line { height: 5.5mm; border-bottom: .5px solid #aeb9c6; }
.key .question { border-left-color: #637b57; }.answer { margin-top: 1.2mm !important; color: #3f6044; background: #ecf3e8; padding: 1.5mm 2mm; border-radius: 1.5mm; }
.student .exercise { break-inside: auto; }
.student .exercise-head { break-after: auto; }
.student .exercise-1,
.student .exercise-2,
.student .exercise-3,
.student .exercise-4,
.student .exercise-5 { break-after: page; }
.student .exercise-6 { padding-top: 14mm; }
.key .exercise-1,
.key .exercise-2,
.key .exercise-3,
.key .exercise-4,
.key .exercise-5 { break-after: page; }
.key .exercise-5 { padding-top: 14mm; }
.key .exercise-5 .exercise-body { padding: 3mm 4mm; }
.key .exercise-5 .exercise-body h3 { margin: 2.4mm 0 1mm; }
.key .exercise-5 .question { padding: 1.25mm 2mm; margin: 1mm 0; font-size: 9.5pt; }
.key .exercise-5 .answer { margin-top: .7mm !important; padding: .9mm 1.5mm; }
.key .exercise-3 .exercise-body { padding: 2.6mm 3.8mm; }
.key .exercise-3 .exercise-body h3 { margin: 1.7mm 0 .7mm; }
.key .exercise-3 .question { padding: .9mm 1.6mm; margin: .55mm 0; font-size: 9.05pt; line-height: 1.24; }
.key .exercise-3 .question p { line-height: 1.24; }
.key .exercise-3 .answer { margin-top: .4mm !important; padding: .55mm 1.2mm; }
code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: .92em; background: #e8ecd8; padding: .2mm .7mm; border-radius: 1mm; }
"""

function exercise_html(exercise; key::Bool=false)
    sections = String[]
    for section in exercise.sections
        section_title = isempty(section.title) ? "" : "<h3>$(inline_html(section.title))</h3>"
        section_intro = isempty(section.introduction) ? "" : "<p>$(inline_html(section.introduction))</p>"
        questions = String[]
        for question in section.questions
            options = isempty(question.options) ? "" : "<div class=\"options\">" * join(("<span class=\"box\">□ $(inline_html(option))</span>" for option in question.options), "") * "</div>"
            response = if key
                "<p class=\"answer\"><b>Answer:</b> $(inline_html(question.answer))</p>"
            elseif isempty(question.options)
                join(fill("<div class=\"answer-line\"></div>", question.answer_lines))
            else
                ""
            end
            push!(questions, "<div class=\"question\"><p><span class=\"qid\">$(inline_html(question.id)).</span> $(inline_html(question.prompt))</p>$options$response</div>")
        end
        push!(sections, "$section_title$section_intro$(join(questions))")
    end
    location = isempty(exercise.location) ? "" : "  $(inline_html(exercise.location))"
    """
    <section class="exercise exercise-$(exercise.number)">
      <header class="exercise-head"><h2>Exercise $(exercise.number) — $(inline_html(exercise.title))</h2><div class="meta">$(inline_html(exercise.notebook))$location  about $(exercise.minutes) minutes</div></header>
      <div class="exercise-body"><p>$(inline_html(exercise.introduction))</p>$(join(sections))</div>
    </section>
    """
end

function printable_html(; key::Bool=false)
    subtitle = key ? "Short answer key, generated from the shared Julia exercise data" : "Beginner worksheet | 30–40 minutes | no proofs or code from scratch"
    intro = key ?
        "Every answer below is stored beside its question in <code>$CONTENT_LABEL</code>." :
        "Open the named Pluto Lab, use only the relevant experiment control, inspect the visual result, and answer briefly. The interactive version is <code>$EXERCISE_NOTEBOOK_LABEL</code>. The themes are adapted at an introductory level from Paul Breiding's Tensorlab exercises; the questions are rederived for TensorKitchen and are not verbatim copies."
    """<!doctype html>
    <html lang="en"><head><meta charset="utf-8"><title>TensorKitchen Exercise $(key ? "Answer Key" : "Sheet")</title><style>$PRINT_CSS</style></head>
    <body class="$(key ? "key" : "student")">
      <header class="banner"><h1>$WORKSHEET_TITLE</h1><div class="author">$WORKSHEET_AUTHOR</div><p>$subtitle</p></header>
      <section class="intro"><p>$intro</p><p>The goal is to distinguish the represented object, its coordinates, the model assumption, and the evidence needed before interpreting components.</p></section>
      $(join((exercise_html(exercise; key) for exercise in EXERCISES)))
    </body></html>"""
end

function main(args = ARGS)
    unknown = setdiff(args, ["--no-pdf"])
    isempty(unknown) || error("Unknown argument(s): $(join(unknown, ", "))")
    mkpath(EXERCISE_DIR)
    mkpath(ANSWER_DIR)

    student_md = joinpath(EXERCISE_DIR, "Exercise_Sheet.md")
    answer_md = joinpath(ANSWER_DIR, "Exercise_Answer_Key.md")
    student_html = joinpath(EXERCISE_DIR, "TensorKitchen_Exercise_Sheet.html")
    answer_html = joinpath(ANSWER_DIR, "TensorKitchen_Exercise_Answer_Key.html")
    write(student_md, student_markdown())
    write(answer_md, answer_markdown())
    write(student_html, printable_html())
    write(answer_html, printable_html(; key=true))

    println("Generated Markdown and print HTML from $CONTENT_LABEL")
    if "--no-pdf" ∈ args
        return
    end

    browser = find_browser()
    isnothing(browser) && error("No Chromium-based browser found. Re-run with --no-pdf and print the generated HTML manually.")
    print_html_pdf(browser, student_html, joinpath(EXERCISE_DIR, "TensorKitchen_Exercise_Sheet.pdf"))
    print_html_pdf(browser, answer_html, joinpath(ANSWER_DIR, "TensorKitchen_Exercise_Answer_Key.pdf"))
    println("Generated exercise PDFs")
end

main()
