#!/usr/bin/env julia

"""Generate the printable glossary LaTeX from the shared Julia content schema."""

const GLOSSARY_ROOT = normpath(joinpath(@__DIR__, ".."))
const GLOSSARY_CONTENT_PATH = joinpath(GLOSSARY_ROOT, "appendix", "GlossaryContent.jl")
const GLOSSARY_TEX_PATH = joinpath(GLOSSARY_ROOT, "appendix", "GlossaryAppendix.tex")

if !isdefined(@__MODULE__, :GlossaryContent)
    include(GLOSSARY_CONTENT_PATH)
end
using .GlossaryContent

function latex_plain(text)
    replace(
        string(text),
        "&" => raw"\&",
        "%" => raw"\%",
        "#" => raw"\#",
        "_" => raw"\_",
        "–" => "--",
        "—" => "---",
        "…" => raw"\ldots{}",
        "≠" => raw"\(\neq\)",
        "≈" => raw"\(\approx\)",
        "≥" => raw"\(\ge\)",
        "≤" => raw"\(\le\)",
        "×" => raw"\(\times\)",
        "→" => raw"\(\rightarrow\)",
        "⊗" => raw"\(\otimes\)",
        "“" => "``",
        "”" => "''",
        "’" => "'",
    )
end

function latex_prose(text)
    parts = split(string(text), '$'; keepempty = true)
    join([
        isodd(index) ? latex_plain(part) : "\$$(part)\$"
        for (index, part) in enumerate(parts)
    ])
end

function entry_latex(entry)
    note = isnothing(entry.note) ? "" : """
\\begin{interpretationnote}{$(latex_plain(entry.note_label))}
$(latex_prose(entry.note))
\\end{interpretationnote}
"""
    citations = isempty(entry.citations) ? "" :
        "\\par\\smallskip{\\small\\color{muted}[$(join(entry.citations, ", "))]}"
    """
\\begin{glossaryentry}{$(latex_plain(entry.term))}
$(latex_prose(entry.summary))
$note$citations
\\end{glossaryentry}
"""
end

function glossary_section(category, title)
    chunks = ["\\section{$(latex_plain(title))}"]
    entries = filter(entry -> entry.category == category, GLOSSARY_ENTRIES)
    for cluster in CLUSTER_ORDER[category]
        cluster_entries = filter(entry -> entry.cluster == cluster, entries)
        isempty(cluster_entries) && continue
        push!(chunks, "\\subsection{$(latex_plain(cluster))}")
        append!(chunks, entry_latex.(cluster_entries))
    end
    join(chunks, "\n\n")
end

function references_latex()
    items = [
        "\\item[\\textbf{[$(reference.short)]}] $(latex_plain(reference.citation))"
        for reference in GLOSSARY_REFERENCES
    ]
    """
\\section{Reference index}
\\begin{description}[leftmargin=1.55cm,style=nextline,itemsep=.55em]
$(join(items, "\n"))
\\end{description}
"""
end

function glossary_document()
    math_section = glossary_section("Mathematics", "Mathematical glossary")
    ai_section = glossary_section("AI & Interpretability", "AI and interpretability glossary")
    reference_section = references_latex()
    """% Generated by scripts/generate_glossary_latex.jl.
% Edit appendix/GlossaryContent.jl, not this file.
\\documentclass[10pt]{article}
\\usepackage[a4paper,margin=2.1cm]{geometry}
\\usepackage[T1]{fontenc}
\\usepackage{lmodern}
\\usepackage{microtype}
\\usepackage{amsmath,amssymb}
\\usepackage{booktabs,longtable,array}
\\usepackage{xcolor}
\\usepackage{hyperref}
\\usepackage{enumitem}
\\usepackage{titlesec}
\\usepackage{parskip}

\\definecolor{mathaccent}{HTML}{3F5F73}
\\definecolor{aiaccent}{HTML}{6B5D45}
\\definecolor{olive}{HTML}{6A7047}
\\definecolor{softgray}{HTML}{F4F4F1}
\\definecolor{muted}{HTML}{66665F}

\\hypersetup{colorlinks=true,linkcolor=olive,urlcolor=mathaccent,citecolor=olive}
\\setlist[itemize]{leftmargin=1.5em,itemsep=0.2em}
\\titleformat{\\section}{\\Large\\bfseries}{}{0pt}{}
\\titleformat{\\subsection}{\\large\\bfseries\\color{olive}}{}{0pt}{}

\\newenvironment{glossaryentry}[1]{%
  \\par\\medskip\\noindent
  {\\large\\bfseries #1}\\par\\smallskip
}{\\par\\medskip}

\\newenvironment{interpretationnote}[1]{%
  \\par\\smallskip\\noindent
  \\begin{minipage}{\\linewidth}
  \\setlength{\\fboxsep}{8pt}%
  \\colorbox{softgray}{\\begin{minipage}{\\dimexpr\\linewidth-2\\fboxsep}
  \\textbf{#1}\\par\\smallskip
}{%
  \\end{minipage}}
  \\end{minipage}\\par\\smallskip
}

\\newcommand{\\keydistinction}[1]{%
\\begin{center}
\\fbox{\\parbox{0.88\\linewidth}{\\centering\\bfseries #1}}
\\end{center}
}

\\title{\\textbf{Low-Rank Structure Is Geometry}\\\\
\\large Mathematical and AI/Interpretability Glossary}
\\author{Companion appendix}
\\date{}

\\begin{document}
\\maketitle

\\begin{abstract}
This optional companion groups mathematical and AI/interpretability vocabulary
by topic. Each entry begins with a compact explanation. Only terms with a
substantial pedagogical caution receive a separate \\emph{Why it matters} or
\\emph{Interpretation boundary} note. Citation keys expand in the final index.
\\end{abstract}

\\tableofcontents
\\newpage

\\section{How to use this glossary}
Read the main notebooks first and use this appendix as a lookup reference.
Definitions remain local to the notebooks; this companion provides additional
precision and a bridge between mathematical and interpretability language.

\\keydistinction{Coordinates are not automatically intrinsic objects. Learned factors are not automatically validated concepts.}

$math_section

\\newpage
$ai_section

\\newpage
\\section{Translation guide: mathematics to interpretability}
\\begin{longtable}{p{0.23\\linewidth} p{0.28\\linewidth} p{0.41\\linewidth}}
\\toprule
\\textbf{Mathematical language} & \\textbf{Interpretability language} & \\textbf{Caution}\\\\
\\midrule
Factor / dictionary atom & Candidate feature or concept direction & A mathematical direction becomes semantic only after validation. \\\\
Coefficient & Feature or concept usage & Presence is not importance. \\\\
Subspace & Representation/update subspace & A stable subspace need not have a unique meaningful basis. \\\\
Rank & Vocabulary capacity / granularity & More rank can split or duplicate concepts. \\\\
Conditioning & Representation stability & Good reconstruction can coexist with fragile coordinates. \\\\
Identifiability & Recoverability & Recoverability is not domain meaning. \\\\
Perturbation / intervention & Behavioral evidence & The claim depends on the intervention and its controls. \\\\
\\bottomrule
\\end{longtable}

\\keydistinction{A mathematically recoverable factor is not automatically a scientifically meaningful concept.}

$reference_section

\\end{document}
"""
end

function generate_glossary_latex()
    write(GLOSSARY_TEX_PATH, glossary_document())
    println("Wrote $GLOSSARY_TEX_PATH from appendix/GlossaryContent.jl")
    GLOSSARY_TEX_PATH
end

if abspath(PROGRAM_FILE) == abspath(@__FILE__)
    generate_glossary_latex()
end
